# Generated by Django 4.2 on 2023-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default_username', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='propensity',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
